pipeline {
  agent any
  
  stages {

    stage('vsim') {
      steps {
        deleteDir() // clean up workspace
        sh '''
        make vsim
        '''
      }
    }


  }
  post {
    failure {
      emailext attachLog: true,
      body: '''
      Project name: $PROJECT_NAME
      Build number: $BUILD_NUMBER
      Build Status: $BUILD_STATUS
      Build URL: $BUILD_URL
      ''',
      recipientProviders: [culprits()],
      subject: 'Project \'$PROJECT_NAME\' is broken'
    }
  }
}
